use_frameworks!

target 'JustPeek_Example' do
  pod 'JustPeek', :path => '../'

  target 'JustPeek_Tests' do
    inherit! :search_paths
  end

  target 'JustPeek_UITests' do
    inherit! :search_paths
  end
end
